version: '3.4'

services:
  kitalatalaclient:
    image: kitalatalaclient
    container_name: kitalatala
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:3000
    volumes:
      - .:/app
      - '/app/node_modules'
      - out:/app/out

volumes:
  out:
