version: '3.4'

services:
  kitalatalaclient:
    image: kitalatalaclient
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:3000
    volumes:
      - .:/app
      - '/app/node_modules'
